// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function Calculate(arg1:string):Promise<number>;

export function GetCurrencies():Promise<Array<string>>;

export function GetDefaultCurrency():Promise<any>;

export function GetDefaultYear():Promise<any>;

export function GetHistory():Promise<Array<model.History>>;

export function GetLanguage():Promise<Array<string>>;

export function GetYears():Promise<Array<string>>;
