// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Calculate(arg1) {
  return window['go']['main']['App']['Calculate'](arg1);
}

export function GetCurrencies() {
  return window['go']['main']['App']['GetCurrencies']();
}

export function GetDefaultCurrency() {
  return window['go']['main']['App']['GetDefaultCurrency']();
}

export function GetDefaultYear() {
  return window['go']['main']['App']['GetDefaultYear']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetLanguage() {
  return window['go']['main']['App']['GetLanguage']();
}

export function GetYears() {
  return window['go']['main']['App']['GetYears']();
}
